"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { apiFetch } from "@/lib/client-utils";

type InvoiceData = {
  id: string;
  invoiceNumber: string;
  clientName: string;
  clientEmail: string;
  amount: number;
  description: string;
  status: string;
  createdAt: string;
  board?: { title?: string };
};

export default function InvoicePage() {
  const params = useParams();
  const id = params?.id as string | undefined;
  const [invoice, setInvoice] = useState<InvoiceData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!id) return;
    apiFetch<{ invoices: InvoiceData[] }>("/api/finance/invoice")
      .then((res) => {
        const found = res.invoices.find((i) => i.id === id);
        setInvoice(found ?? null);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) return <div className="flex min-h-screen items-center justify-center">Loading...</div>;
  if (!invoice) return <div className="flex min-h-screen items-center justify-center">Invoice not found.</div>;

  return (
    <div className="min-h-screen bg-white p-8 print:p-4">
      <div className="mx-auto max-w-3xl">
        <div className="mb-8 flex items-center justify-between">
          <h1 className="text-2xl font-bold">Invoice</h1>
          <button
            className="rounded-lg bg-slate-950 px-4 py-2 text-sm text-white print:hidden"
            onClick={() => window.print()}
          >
            Download PDF
          </button>
        </div>

        <div className="border-b border-slate-200 pb-6">
          <p className="text-lg font-semibold">{invoice.invoiceNumber}</p>
          <p className="text-sm text-slate-500">{new Date(invoice.createdAt).toLocaleDateString()}</p>
        </div>

        <div className="mt-6 grid gap-6 md:grid-cols-2">
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Client</p>
            <p className="mt-1 font-medium">{invoice.clientName}</p>
            {invoice.clientEmail ? <p className="text-sm text-slate-500">{invoice.clientEmail}</p> : null}
          </div>
          <div className="text-right">
            <p className="text-xs font-medium uppercase tracking-wider text-slate-500">Status</p>
            <span className={`mt-1 inline-block rounded-full px-3 py-1 text-xs font-medium ${invoice.status === "paid" ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}>
              {invoice.status}
            </span>
          </div>
        </div>

        {invoice.board?.title ? (
          <p className="mt-4 text-sm text-slate-500">Project: {invoice.board.title}</p>
        ) : null}

        <div className="mt-8 border-t border-slate-200 pt-6">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs font-medium uppercase text-slate-500">
                <th className="pb-3">Description</th>
                <th className="pb-3 text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="py-4">{invoice.description || "Professional services"}</td>
                <td className="py-4 text-right">₹{invoice.amount.toLocaleString("en-IN")}</td>
              </tr>
            </tbody>
            <tfoot>
              <tr className="border-t border-slate-200 text-base font-semibold">
                <td className="pt-4">Total</td>
                <td className="pt-4 text-right">₹{invoice.amount.toLocaleString("en-IN")}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        <p className="mt-12 text-center text-xs text-slate-400">Generated by FlowZen Finance</p>
      </div>
    </div>
  );
}
